# Generated by Django 5.0.7 on 2024-08-02 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trending',
            fields=[
                ('tv_id', models.IntegerField(primary_key=True, serialize=False)),
                ('backdrop_path', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('overview', models.TextField()),
                ('poster_path', models.CharField(max_length=255)),
                ('adult', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('tv_id', models.OneToOneField(db_column='cast_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tv.trending')),
                ('cast_names', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('tv_id', models.OneToOneField(db_column='details_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tv.trending')),
                ('last_episode_name', models.CharField(blank=True, max_length=255, null=True)),
                ('genres', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('tv_id', models.OneToOneField(db_column='video_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tv.trending')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
            ],
        ),
    ]
